export const relationsHeadersMapping = {
  'Id de la structure': 'resourceId',
  'Id de la personne': 'relatedObjectId',
  'Id du poste': 'relationTypeId',
  'Raison du mandat [E = election, N = nomination]': 'mandateReason',
  'Mandat par intérim [O = Oui, N = NON]': 'mandateTemporary',
  'Position du mandat [1 = 1er mandat, 2 = 2 ème mandat, 3 = 3 ème mandat ou vide]': 'mandatePosition',
  'Adresse mail associée au mandat': 'mandateEmail',
  'Adresse mail nominative': 'personalEmail',
  'Numéro de téléphone': 'mandatePhonenumber',
  'Mandat Actif [O = oui, N = non]': 'active',
  'Date de début du mandat': 'startDate',
  'Date de fin prévisionnelle': 'endDatePrevisional',
  'Date de fin du mandat': 'endDate',
  'Date de fin inconnue mais passée [O = oui, N = non]': 'active',
};
