export const INTERNAL_PAGES_TYPES = [
  'website',
  'websiteRss',
  'websiteOrganizationChart',
  'websiteGovernance',
  'websiteGeneralServices',
  'websiteCommunication',
  'websiteSocialReport',
  'websiteActivityReport',
  'websitePress',
  'websitenews',
  'websiteDirectory',
  'websiteCatForm',
  'websiteAcademicComponents',
  'websiteHistory',
  'websitePhotoLibrary',
  'websiteNewsCast',
  '',
];

export const WEBLINKS_TYPES = [
  'Hal',
  'Onisep',
  'POpenData',
  'DataGouvFr',
  'scanR',
  'mooc',
  'CanalU',
  'ServicePublic',
  'PiaWEB',
  // 'Sujet d\'actualités sur le site web du journal Le Monde'
  'EdCF',
  'OE1',
  'OE2',
  'OE3',
  'hceres',
  'EducPros',
  'IUF',
  'jorfsearch',
  'TalentCNRS',
  'TheConversation',
  'Lieux inspirants',
  'BSO',
  '',
];

export const PALMARES_TYPES = [
  'rankingShanghai',
  'rankingThe',
  'rankingScimago',
  'rankingQs',
  'rankingUmultirank',
  'rankingLeiden',
  'rankingWebometrics',
  '',
];
