export const KEEP_TYPES = [
  '',
  'Hal',
  'Onisep',
  'POpenData',
  'DataGouvFr',
  'scanR',
  'mooc',
  'CanalU',
  'ServicePublic',
  // 'Sujet d\'actualités sue le site web du journal Le Monde'
  'EdCF',
  'OE1',
  'OE2',
  'OE3',
  'hceres',
  'EducPros',
  'IUF',
  'jorfsearch',
  'TalentCNRS',
  'TheConversation',
];
