export const ENUMS_LABELS_MAPPER = {
  website: 'Site internet',
  websiteRss: 'Flux RSS',
  websiteOrganizationChart: 'Page sur l\'organisation/organigramme',
  websiteGovernance: 'Page gouvernance',
  websiteGeneralServices: 'Page services généraux',
  websiteCommunication: 'Service communication',
  // Page avec le lien vers l'organigramme
  websiteSocialReport: 'Page bilan social',
  websiteActivityReport: 'Page rapport d\'activité',
  websitePress: 'Espace presse',
  websitenews: 'Actualités',
  websiteDirectory: 'Annuaire en ligne',
  websiteCatForm: 'Catalogue de formations',
  websiteAcademicComponents: 'Page liste des composantes',
  websiteHistory: 'Page histoire',
  websitePhotoLibrary: 'Photothèque',
  websiteNewsCast: 'websiteNewsCast',
  PiaWEB: 'Données PiaWEB',
  Hal: 'Portail HAL',
  Onisep: 'Page Onisep.fr',
  POpenData: 'Plateforme Opendata',
  DataGouvFr: 'Page sur data.gouv.fr',
  scanR: 'Page scanR',
  mooc: 'Compte FUN',
  CanalU: 'Canal-U',
  ServicePublic: 'Annuaire service public',
  // 'Sujet d\'actualités sur le site web du journal Le Monde'
  EdCF: 'Annuaire des écoles doctorales, campus France',
  OE1: 'Editeur chez openedition',
  OE2: 'Revues chez openedition',
  OE3: 'Carnets Hypotheses OpenEdition',
  hceres: 'Evaluations HCERES',
  EducPros: 'EducPros',
  IUF: 'IUF',
  jorfsearch: 'jorfsearch',
  TalentCNRS: 'TalentCNRS',
  TheConversation: 'TheConversation',
  personal: 'Page personnelle',
  official: 'Page officielle',
  // structures ranking
  rankingShanghai: 'Classement de Shanghai',
  rankingThe: 'Classement de TimeHigherEducation',
  rankingScimago: 'Classement Scimago',
  rankingQs: 'Classement QS',
  rankingUmultirank: 'Classement Umultirank',
  rankingLeiden: 'Classement de Leiden',
  rankingWebometrics: 'Classement Webometrics',
  // type of Identifiers
  BibId: 'ESGBU - id bibliothèque',
  bnf: 'Identifiant BnF',
  CJ3: 'Catégorie juridique INSEE (niveau III)',
  CTI: 'Identifiant CTI',
  ED: "Numéro de l'ED",
  ETER: 'ETER id',
  EtId: 'ESGBU - id établissement',
  finess: 'FINESS id',
  fundr: 'FUNDREF id',
  'GA OAD': 'RTOAD id',
  GRID: 'GRID id',
  'id annelis': 'ANNELIS id',
  'Id unité CNRS': 'CNRS id',
  'Identifiant CTI de l\'école': 'CTI id',
  idhal: 'HAL id',
  idref: 'idRef',
  ISIL: 'ISIL id',
  isni: 'ISNI',
  IS03: 'Code ISO 3',
  ISO2: 'Code ISO 2',
  'Numéro d\'ED': 'ED id',
  nnt: 'Numéro national de Thèse',
  'OpenCorporates ID': 'OpenCorporate id',
  orcid: 'Orcid',
  orgref: 'ORGREF id',
  PIA: 'Identifiant Référence projet PIA',
  'PIC (Participant Identification Code)': 'PIC id',
  PSUP: 'Lib formation Parcoursup',
  PSUP2: 'Lib formation en apprentissage Parcoursup',
  PSUPC: 'Lib informations complémentaires Parcoursup',
  PSUPT: 'Lib types de formation Parcoursup',
  RCR: 'RCR id',
  'Référence projet PIA (ANR)': 'ANR - id projet PIA',
  ringgold: 'RINGGOLD id',
  RNA: 'RNA id',
  RNSR: 'RNSR id',
  ROR: 'ROR id',
  scopus: 'Scopus id',
  SIREN: 'SIREN',
  SIRET: 'SIRENE - Siret',
  SsId: 'ESGBU - id service documentaire',
  TVA: 'Numéro de TVA intracommunautaire',
  UAI: 'UAI',
  'univ-droit': 'Univ-droit id',
  wikidata: 'WIKIDATA id',
  wos: 'WOS Researcher ID',
};

export const STRUCTURES_CREATION_REASONS = [
  'Création',
  'Essaimage',
  'Fusion',
  'Scission fusion',
  'Scission',
  'Subtitution',
  'Succession',
  'autre',
];

export const STRUCTURES_CLOSURE_REASONS = [
  'Dissolution',
  'Fusion',
  'Intégration',
  'Liquidation',
  'Scission',
  'Subtitution',
  'Succession',
  'autre',
];

// TODO: Restore projects
// export const SEARCH_TYPES = 'categories%2Cofficial%2Dtexts%2Cpersons%2Cprizes%2Cprojects%2Cstructures%2Cterms';
export const SEARCH_TYPES = 'categories%2Cofficial%2Dtexts%2Cpersons%2Cprizes%2Cstructures%2Cterms';
