export const ENUMS_LABELS_MAPPER = {
  website: 'Lien web',
  websiteRss: 'Flux RSS',
  websiteOrganizationChart: 'Page sur l\'organisation/organigramme',
  websiteGovernance: 'Page gouvernance',
  websiteGeneralServices: 'Page services généraux',
  websiteCommunication: 'Service communication',
  // Page avec le lien vers l'organigramme
  websiteSocialReport: 'Page bilan social',
  websiteActivityReport: 'Page rapport d\'activité',
  websitePress: 'Espace presse',
  websitenews: 'Actualités',
  websiteDirectory: 'Annuaire en ligne',
  websiteCatForm: 'Catalogue de formations',
  websiteAcademicComponents: 'Page liste des composantes',
  websiteHistory: 'Page histoire',
  websitePhotoLibrary: 'Photothèque',
  websiteNewsCast: 'websiteNewsCast',
  Hal: 'Portail HAL',
  Onisep: 'Page Onisep.fr',
  POpenData: 'Plateforme Opendata',
  DataGouvFr: 'Page sur data.gouv.fr',
  scanR: 'Page scanR',
  mooc: 'Compte FUN',
  CanalU: 'Canal-U',
  ServicePublic: 'Annuaire service public',
  // 'Sujet d\'actualités sue le site web du journal Le Monde'
  EdCF: 'Annuaire des écoles doctorales, campus France',
  OE1: 'Editeur chez openedition',
  OE2: 'Revues chez openedition',
  OE3: 'Carnets Hypotheses OpenEdition',
  hceres: 'Page HCERES',
  EducPros: 'EducPros',
  IUF: 'IUF',
  jorfsearch: 'jorfsearch',
  TalentCNRS: 'TalentCNRS',
  TheConversation: 'TheConversation',
};

export const STRUCTURES_CREATION_REASONS = [
  'Création',
  'Essaimage',
  'Fusion',
  'Scission fusion',
  'Scission',
  'Subtitution',
  'Succession',
  'autre',
];

export const STRUCTURES_CLOSURE_REASONS = [
  'Dissolution',
  'Fusion',
  'Intégration',
  'Liquidation',
  'Scission',
  'Subtitution',
  'Succession',
  'autre',
];
