export const ENUMS_LABELS_MAPPER = {
  website: 'Site internet',
  websiteRss: 'Flux RSS',
  websiteOrganizationChart: 'Page sur l\'organisation/organigramme',
  websiteGovernance: 'Page gouvernance',
  websiteGeneralServices: 'Page services généraux',
  websiteCommunication: 'Service communication',
  // Page avec le lien vers l'organigramme
  websiteSocialReport: 'Page bilan social',
  websiteActivityReport: 'Page rapport d\'activité',
  websitePress: 'Espace presse',
  websitenews: 'Actualités',
  websiteDirectory: 'Annuaire en ligne',
  websiteCatForm: 'Catalogue de formations',
  websiteAcademicComponents: 'Page liste des composantes',
  websiteHistory: 'Page histoire',
  websitePhotoLibrary: 'Photothèque',
  websiteNewsCast: 'websiteNewsCast',
  Hal: 'Portail HAL',
  Onisep: 'Page Onisep.fr',
  POpenData: 'Plateforme Opendata',
  DataGouvFr: 'Page sur data.gouv.fr',
  scanR: 'Page scanR',
  mooc: 'Compte FUN',
  CanalU: 'Canal-U',
  ServicePublic: 'Annuaire service public',
  // 'Sujet d\'actualités sue le site web du journal Le Monde'
  EdCF: 'Annuaire des écoles doctorales, campus France',
  OE1: 'Editeur chez openedition',
  OE2: 'Revues chez openedition',
  OE3: 'Carnets Hypotheses OpenEdition',
  hceres: 'Evaluations HCERES',
  EducPros: 'EducPros',
  IUF: 'IUF',
  jorfsearch: 'jorfsearch',
  TalentCNRS: 'TalentCNRS',
  TheConversation: 'TheConversation',
  personal: 'Page personnelle',
  official: 'Page officielle',
  // structures ranking
  rankingShanghai: 'Classement de Shanghai',
  rankingThe: 'Classement de TimeHigherEducation',
  rankingScimago: 'Classement Scimago',
  rankingQs: 'Classement QS',
  rankingUmultirank: 'Classement Umultirank',
  rankingLeiden: 'Classement de Leiden',
  rankingWebometrics: 'Classement Webometrics',
  // type of Identifiers
  ALId: 'Identifiant Annelis',
  BibId: 'Identifiant bibliothèque ESGBU',
  BNF: 'Identifiant BnF',
  CJ3: 'Catégorie juridique INSEE (niveau III)',
  cvHal: 'Identifiant cvHal',
  CTI: 'Identifiant CTI',
  dataESR: 'Identifiant dataESR',
  ED: "Numéro de l'ED",
  ETER: 'Identifiant ETER',
  EtId: 'Identifiant établissement ESGBU',
  fundr: 'Identifiant fundref',
  GRID: 'Identifiant GRID',
  isni: 'Identifiant Isni',
  ISIL: 'Identifiant ISIL',
  IdREF: 'Identifiant IdRef',
  idHal: 'Identifiant idHal',
  IS03: 'Code ISO 3',
  ISO2: 'Code ISO 2',
  OAD: 'Identifiant GA OAD',
  ORCID: 'ORCID iD',
  orgre: 'Identifiant orgref',
  UAI: 'Code UAI',
  UNIVD: 'Identifiant Univ-droit',
  PIC: 'PIC',
  PIA: 'Identifiant Référence projet PIA',
  PSUP: 'Lib formation Parcoursup',
  PSUP2: 'Lib formation en apprentissage Parcoursup',
  PSUPT: 'Lib types de formation Parcoursup',
  PSUPC: 'Lib informations complémentaires Parcoursup',
  RCR: 'Identifiant RCR',
  RNA: 'Répertoire national des associations',
  RNSR: 'Identifiant RNSR',
  SsId: 'Identifiant service documentaire ESGB',
  SIREN: 'SIREN',
  SIRET: 'SIRET',
  TVA: 'Numéro de TVA intracommunautaire',
  These: 'Numéro national de thèse',
};

export const STRUCTURES_CREATION_REASONS = [
  'Création',
  'Essaimage',
  'Fusion',
  'Scission fusion',
  'Scission',
  'Subtitution',
  'Succession',
  'autre',
];

export const STRUCTURES_CLOSURE_REASONS = [
  'Dissolution',
  'Fusion',
  'Intégration',
  'Liquidation',
  'Scission',
  'Subtitution',
  'Succession',
  'autre',
];
