export default {
  Prénom: 'firstName',
  Nom: 'lastName',
  'Genre [F = Femme, H = Homme, A = Autre]': 'gender',
  'Date de naissance {1990-05-21}': 'birthDate',
  'Code de la/des catégories {rechercher le code, séparation ;}': 'categories',
  Activité: 'activity',
  'Identifiant Orcid': 'orcid',
  'Identifiant Wikidata [Q1234]': 'wikidata',
  'Identifiant IdRef [123456789]': 'idref',
  'Compte twitter [https://twitter.com/XXX]': 'twitter',
  'Site internet en français': 'websiteFr',
  'Site internet en anglais': 'websiteEn',
  'Compte linkedIn [https://www.linkedin.com/in/XXX-XXX-123456/]': 'linkedIn',
  'Dans la recherche publique ? [O : Oui, N : Non]:': 'publicSearch',
};
