name: Tests

on:
  push:
    branches:
      - staging
      
env:
  DEPLOYMENT_URL: https://paysage.staging.dataesr.ovh/
  MM_NOTIFICATION_CHANNEL: 'bots'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --silent
      - name: Run tests
        run: npm test

  notify:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          mattermost_channel: ${{ env.MM_NOTIFICATION_CHANNEL}}
          deployment_url: ${{ env.DEPLOYMENT_URL }}